#ifndef SRC_STATUSES_STATUSCONSTANTS_H_
#define SRC_STATUSES_STATUSCONSTANTS_H_

const double MOD_SCALING_FACTOR = 0.2;

const double SP_UPSCALING_FACTOR = 1.0;
const double SP_DOWNSCALING_FACTOR = 0.5;

const double MP_COST_UPSCALING_FACTOR = 2.0;
const double MP_COST_DOWNSCALING_FACTOR = 0.5;

#endif
